-- ===========================================================================
-- Extra portfolios per user (Family plan, phase 1).
-- Spec: docs/security/encryption.md §15.1.
--
-- The personal portfolio stays in portfolio_snapshots. These tables hold the
-- extra ones: each blob is encrypted under its own portfolio key (PK), and
-- each member row holds that PK wrapped under the member's DK. The server
-- stores ciphertext and membership only.
--
-- Clients may read and delete, but never INSERT or UPDATE directly: every
-- write goes through the SECURITY DEFINER functions below, which set the
-- owner and the revision themselves so a client can forge neither.
--
-- family_beta grants Family features before the Stripe plan exists. It is
-- service-role only; check-subscription reads it.
-- ===========================================================================

create table public.portfolios (
  id             uuid primary key,  -- generated by the client: it is bound into the AAD before the row exists
  owner_id       uuid not null references auth.users(id) on delete restrict,
  encrypted_data bytea not null,
  nonce          bytea not null check (octet_length(nonce) = 24),
  enc_version    integer not null check (enc_version = 1),
  revision       bigint not null default 1,
  key_epoch      integer not null default 1 check (key_epoch >= 1),
  rotation_due   boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- RESTRICT on owner_id: account deletion must remove (or, once sharing
-- exists, transfer) portfolios explicitly, so a missed step fails the
-- deletion instead of silently cascading a portfolio away.
create index portfolios_owner_id_idx on public.portfolios (owner_id);

create trigger update_portfolios_updated_at
  before update on public.portfolios
  for each row execute function public.update_updated_at_column();

create table public.portfolio_members (
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  -- PK wrapped under this member's DK: nonce(24) || ciphertext_with_tag(48).
  wrapped_pk   bytea not null check (octet_length(wrapped_pk) = 72),
  key_epoch    integer not null check (key_epoch >= 1),
  created_at   timestamptz not null default now(),
  primary key (portfolio_id, user_id)
);

create index portfolio_members_user_id_idx on public.portfolio_members (user_id);

create table public.family_beta (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  note       text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Membership check for RLS. SECURITY DEFINER because the portfolio_members
-- SELECT policy calls it, and an invoker function reading the same table
-- from its own policy would recurse.
-- ---------------------------------------------------------------------------
create function public.is_portfolio_member(_portfolio_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portfolio_members
    where portfolio_id = _portfolio_id and user_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.portfolios        enable row level security;
alter table public.portfolio_members enable row level security;
alter table public.family_beta       enable row level security;

create policy "owners and members can read portfolios"
  on public.portfolios for select to authenticated
  using (owner_id = auth.uid() or public.is_portfolio_member(id));

create policy "owners can delete portfolios"
  on public.portfolios for delete to authenticated
  using (owner_id = auth.uid());

create policy "members can read memberships of their portfolios"
  on public.portfolio_members for select to authenticated
  using (user_id = auth.uid() or public.is_portfolio_member(portfolio_id));

-- family_beta: no policies. Only service_role (edge functions) reads it.

-- ---------------------------------------------------------------------------
-- Grants. New tables still auto-grant to anon/authenticated until the
-- 2026-10-30 cutoff (see 20260514000000), so revoke first.
-- ---------------------------------------------------------------------------
revoke all on public.portfolios        from anon, authenticated;
revoke all on public.portfolio_members from anon, authenticated;
revoke all on public.family_beta       from anon, authenticated;

grant select, delete on public.portfolios        to authenticated;
grant select         on public.portfolio_members to authenticated;
grant all            on public.portfolios        to service_role;
grant all            on public.portfolio_members to service_role;
grant all            on public.family_beta       to service_role;

-- ---------------------------------------------------------------------------
-- create_portfolio: the only way to add a portfolio. The caller becomes the
-- owner and first member. At most 5 per owner; the advisory lock serialises
-- concurrent creates by the same user so the count can't be raced.
-- ---------------------------------------------------------------------------
create function public.create_portfolio(
  p_id             uuid,
  p_wrapped_pk     bytea,
  p_encrypted_data bytea,
  p_nonce          bytea,
  p_enc_version    integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _uid uuid := auth.uid();
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('create_portfolio:' || _uid::text, 0));

  if (select count(*) from public.portfolios where owner_id = _uid) >= 5 then
    raise exception 'portfolio_limit';
  end if;

  insert into public.portfolios (id, owner_id, encrypted_data, nonce, enc_version)
  values (p_id, _uid, p_encrypted_data, p_nonce, p_enc_version);

  insert into public.portfolio_members (portfolio_id, user_id, wrapped_pk, key_epoch)
  values (p_id, _uid, p_wrapped_pk, 1);
end;
$$;

-- ---------------------------------------------------------------------------
-- save_portfolio: compare-and-swap on (revision, key_epoch).
--   ok        -> written; current_revision is the new revision
--   conflict  -> someone else wrote first, or the key was rotated;
--                current_revision is what's stored now
--   forbidden -> no such portfolio, or the caller isn't a member
-- A bare UPDATE can't tell "conflict" from "lost access": RLS hides both.
-- ---------------------------------------------------------------------------
create function public.save_portfolio(
  p_id                uuid,
  p_expected_revision bigint,
  p_key_epoch         integer,
  p_encrypted_data    bytea,
  p_nonce             bytea,
  p_enc_version       integer
)
returns table (status text, current_revision bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  _uid      uuid := auth.uid();
  _revision bigint;
  _epoch    integer;
begin
  select p.revision, p.key_epoch into _revision, _epoch
  from public.portfolios p
  where p.id = p_id
  for update;

  if not found or not exists (
    select 1 from public.portfolio_members m
    where m.portfolio_id = p_id and m.user_id = _uid
  ) then
    return query select 'forbidden'::text, null::bigint;
    return;
  end if;

  if _revision <> p_expected_revision or _epoch <> p_key_epoch then
    return query select 'conflict'::text, _revision;
    return;
  end if;

  update public.portfolios p
  set encrypted_data = p_encrypted_data,
      nonce          = p_nonce,
      enc_version    = p_enc_version,
      revision       = _revision + 1
  where p.id = p_id;

  return query select 'ok'::text, _revision + 1;
end;
$$;

revoke execute on function public.is_portfolio_member(uuid)                               from public, anon;
revoke execute on function public.create_portfolio(uuid, bytea, bytea, bytea, integer)       from public, anon;
revoke execute on function public.save_portfolio(uuid, bigint, integer, bytea, bytea, integer) from public, anon;
grant  execute on function public.is_portfolio_member(uuid)                               to authenticated, service_role;
grant  execute on function public.create_portfolio(uuid, bytea, bytea, bytea, integer)       to authenticated, service_role;
grant  execute on function public.save_portfolio(uuid, bigint, integer, bytea, bytea, integer) to authenticated, service_role;
