-- ===========================================================================
-- Sharing an extra portfolio with one partner (Family plan, phase 2).
-- Spec: docs/security/encryption.md §7.3, §8.7–§8.10.
--
-- The owner invites a partner by email. The portfolio key (PK) travels
-- wrapped under a secret S that exists only in the invite link's fragment,
-- so the server never holds anything that opens the portfolio. The partner
-- accepts by re-wrapping PK under their own DK.
--
-- One partner per owner (family_partners). Removing the partner, or the
-- partner leaving, sets rotation_due; the owner's browser then re-encrypts
-- under a new PK (rotate_portfolio_key).
--
-- As in phase 1, clients never INSERT or UPDATE these tables directly:
-- writes go through the SECURITY DEFINER functions below. The exceptions are
-- DELETEs a policy allows: an owner revoking an invite or removing the
-- partner, and a partner leaving.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Who wrote the current blob, and when. A trigger sets both whenever the
-- ciphertext changes, so a flag change (rotation_due) doesn't count as a save.
-- ---------------------------------------------------------------------------
alter table public.portfolios
  add column saved_at timestamptz not null default now(),
  add column saved_by uuid default auth.uid() references auth.users(id) on delete set null;

create function public.stamp_portfolio_save()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.encrypted_data is distinct from old.encrypted_data then
    new.saved_at := now();
    new.saved_by := auth.uid();
  end if;
  return new;
end;
$$;

create trigger stamp_portfolio_save
  before update on public.portfolios
  for each row execute function public.stamp_portfolio_save();

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- The one partner seat per owner. partner_id is unique too: a person can be
-- the partner of only one owner.
create table public.family_partners (
  owner_id   uuid primary key references auth.users(id) on delete cascade,
  partner_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (owner_id <> partner_id)
);

create table public.portfolio_invites (
  id                uuid primary key,  -- generated by the client: it is bound into the invite wrap's AAD
  portfolio_id      uuid not null references public.portfolios(id) on delete cascade,
  created_by        uuid not null references auth.users(id) on delete cascade,
  invitee_email     text not null check (invitee_email = lower(invitee_email) and length(invitee_email) between 3 and 320),
  -- PK wrapped under the link secret S: nonce(24) || ciphertext_with_tag(48).
  -- Present exactly while the invite is pending; accepting clears it.
  wrapped_pk_invite bytea check (wrapped_pk_invite is null or octet_length(wrapped_pk_invite) = 72),
  key_epoch         integer not null check (key_epoch >= 1),
  expires_at        timestamptz not null default now() + interval '7 days',
  consumed_at       timestamptz,
  consumed_by       uuid references auth.users(id) on delete set null,
  created_at        timestamptz not null default now(),
  check ((consumed_at is null) = (wrapped_pk_invite is not null))
);

create index portfolio_invites_created_by_idx on public.portfolio_invites (created_by);
-- At most one pending invite per portfolio; creating another replaces it.
create unique index portfolio_invites_one_pending_idx
  on public.portfolio_invites (portfolio_id) where consumed_at is null;

-- The ciphertexts a save replaced, newest 20 per portfolio. Lets a member put
-- back a version after a bad write, such as a partner overwriting the blob.
create table public.portfolio_revisions (
  portfolio_id   uuid not null references public.portfolios(id) on delete cascade,
  revision       bigint not null,
  key_epoch      integer not null,
  encrypted_data bytea not null,
  nonce          bytea not null,
  enc_version    integer not null,
  saved_by       uuid references auth.users(id) on delete set null,
  saved_at       timestamptz not null,
  primary key (portfolio_id, revision)
);

-- The owner's wrap of each retired PK. A rotation replaces the owner's
-- member row, and without the old wrap the revisions written before it could
-- no longer be opened, which is exactly when they're needed. The removed
-- partner already knew these keys, so keeping them costs nothing.
create table public.portfolio_key_history (
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  key_epoch    integer not null,
  user_id      uuid not null references auth.users(id) on delete cascade,
  wrapped_pk   bytea not null check (octet_length(wrapped_pk) = 72),
  primary key (portfolio_id, key_epoch, user_id)
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Family access. Phase 3 adds the paid plan next to the beta list.
create function public.has_family(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.family_beta where user_id = _user_id);
$$;

create function public.is_portfolio_owner(_portfolio_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portfolios
    where id = _portfolio_id and owner_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- Membership triggers
-- ---------------------------------------------------------------------------

-- Anyone other than the owner must be the owner's partner.
create function public.enforce_portfolio_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _owner uuid;
begin
  select owner_id into _owner from public.portfolios where id = new.portfolio_id;
  if _owner is not null and new.user_id <> _owner and not exists (
    select 1 from public.family_partners
    where owner_id = _owner and partner_id = new.user_id
  ) then
    raise exception 'not_partner' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger enforce_portfolio_member
  before insert on public.portfolio_members
  for each row execute function public.enforce_portfolio_member();

-- A partner left or was removed: the owner must rotate the key, and any
-- invite still pending wraps the old key. The seat frees once the partner is
-- in none of the owner's portfolios.
--
-- When the whole portfolio is being deleted its row is already gone here,
-- so the update matches nothing; the seat check still runs.
create function public.after_portfolio_member_removed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.portfolios
  set rotation_due = true
  where id = old.portfolio_id and owner_id <> old.user_id;

  if found then
    delete from public.portfolio_invites
    where portfolio_id = old.portfolio_id and consumed_at is null;
  end if;

  delete from public.family_partners fp
  where fp.partner_id = old.user_id
    and not exists (
      select 1
      from public.portfolio_members m
      join public.portfolios p on p.id = m.portfolio_id
      where p.owner_id = fp.owner_id and m.user_id = fp.partner_id
    );
  return old;
end;
$$;

create trigger after_portfolio_member_removed
  after delete on public.portfolio_members
  for each row execute function public.after_portfolio_member_removed();

-- Keep the version a save replaced, then trim to the newest 20, and drop
-- retired keys no kept version needs any more.
create function public.record_portfolio_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.portfolio_revisions
    (portfolio_id, revision, key_epoch, encrypted_data, nonce, enc_version, saved_by, saved_at)
  values
    (old.id, old.revision, old.key_epoch, old.encrypted_data, old.nonce, old.enc_version, old.saved_by, old.saved_at)
  on conflict (portfolio_id, revision) do nothing;

  delete from public.portfolio_revisions
  where portfolio_id = old.id
    and revision < (
      select r.revision from public.portfolio_revisions r
      where r.portfolio_id = old.id
      order by r.revision desc
      offset 19 limit 1
    );

  delete from public.portfolio_key_history h
  where h.portfolio_id = old.id
    and h.key_epoch < (
      select min(r.key_epoch) from public.portfolio_revisions r
      where r.portfolio_id = old.id
    );
  return new;
end;
$$;

create trigger record_portfolio_revision
  after update of encrypted_data on public.portfolios
  for each row
  when (old.encrypted_data is distinct from new.encrypted_data)
  execute function public.record_portfolio_revision();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.family_partners       enable row level security;
alter table public.portfolio_invites     enable row level security;
alter table public.portfolio_revisions   enable row level security;
alter table public.portfolio_key_history enable row level security;

create policy "owners and partners can read their seat"
  on public.family_partners for select to authenticated
  using (owner_id = auth.uid() or partner_id = auth.uid());

create policy "owners can read their invites"
  on public.portfolio_invites for select to authenticated
  using (created_by = auth.uid());

create policy "owners can revoke pending invites"
  on public.portfolio_invites for delete to authenticated
  using (created_by = auth.uid() and consumed_at is null);

create policy "members can read revisions"
  on public.portfolio_revisions for select to authenticated
  using (public.is_portfolio_member(portfolio_id));

create policy "users can read their retired keys"
  on public.portfolio_key_history for select to authenticated
  using (user_id = auth.uid());

-- A partner may leave, and the owner may remove the partner. Nobody can
-- delete the owner's own row, so a partner can't lock the owner out.
create policy "partners can leave and owners can remove them"
  on public.portfolio_members for delete to authenticated
  using (
    (user_id = auth.uid() and not public.is_portfolio_owner(portfolio_id))
    or (user_id <> auth.uid() and public.is_portfolio_owner(portfolio_id))
  );

-- ---------------------------------------------------------------------------
-- Grants. New tables still auto-grant to anon/authenticated until the
-- 2026-10-30 cutoff (see 20260514000000), so revoke first.
-- ---------------------------------------------------------------------------
revoke all on public.family_partners       from anon, authenticated;
revoke all on public.portfolio_invites     from anon, authenticated;
revoke all on public.portfolio_revisions   from anon, authenticated;
revoke all on public.portfolio_key_history from anon, authenticated;

grant select         on public.family_partners       to authenticated;
grant select, delete on public.portfolio_invites     to authenticated;
grant select         on public.portfolio_revisions   to authenticated;
grant select         on public.portfolio_key_history to authenticated;
grant delete         on public.portfolio_members     to authenticated;

grant all on public.family_partners       to service_role;
grant all on public.portfolio_invites     to service_role;
grant all on public.portfolio_revisions   to service_role;
grant all on public.portfolio_key_history to service_role;

-- ---------------------------------------------------------------------------
-- create_portfolio_invite: owner only, with Family, not while a rotation is
-- due, and for the key epoch the portfolio is on now. Replaces any invite
-- still pending for the portfolio. Once a partner holds the seat, invites
-- can only go to that partner.
-- ---------------------------------------------------------------------------
create function public.create_portfolio_invite(
  p_invite_id     uuid,
  p_portfolio_id  uuid,
  p_invitee_email text,
  p_wrapped_pk    bytea,
  p_key_epoch     integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _uid       uuid := auth.uid();
  _email     text := lower(trim(p_invitee_email));
  _portfolio public.portfolios%rowtype;
  _invitee   uuid;
  _partner   uuid;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into _portfolio from public.portfolios where id = p_portfolio_id for update;
  if not found or _portfolio.owner_id <> _uid then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if not public.has_family(_uid) then
    raise exception 'family_required' using errcode = '42501';
  end if;
  if _portfolio.rotation_due then
    raise exception 'rotation_due';
  end if;
  if _portfolio.key_epoch <> p_key_epoch then
    raise exception 'stale_epoch';
  end if;
  if _email !~ '^[^@[:space:]]+@[^@[:space:]]+$' then
    raise exception 'invalid_email';
  end if;
  if _email = (select lower(email) from auth.users where id = _uid) then
    raise exception 'self_invite';
  end if;

  select id into _invitee from auth.users where lower(email) = _email;
  if _invitee is not null and exists (
    select 1 from public.portfolio_members
    where portfolio_id = p_portfolio_id and user_id = _invitee
  ) then
    raise exception 'already_member';
  end if;

  select partner_id into _partner from public.family_partners where owner_id = _uid;
  if _partner is not null and _invitee is distinct from _partner then
    raise exception 'seat_taken';
  end if;

  delete from public.portfolio_invites
  where portfolio_id = p_portfolio_id and consumed_at is null;

  insert into public.portfolio_invites (id, portfolio_id, created_by, invitee_email, wrapped_pk_invite, key_epoch)
  values (p_invite_id, p_portfolio_id, _uid, _email, p_wrapped_pk, p_key_epoch);
end;
$$;

-- ---------------------------------------------------------------------------
-- Invite checks shared by get_ and accept_portfolio_invite. Returns 'ok' or
-- the reason the caller can't use the invite. Statuses that describe the
-- invite (used, expired, ...) come only after the email matches, so a
-- stranger holding the id learns nothing but "not for you".
-- ---------------------------------------------------------------------------
create function public.portfolio_invite_status(_invite public.portfolio_invites, _uid uuid)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  _email     text;
  _confirmed timestamptz;
  _owner     uuid;
  _epoch     integer;
  _partner   uuid;
begin
  select owner_id, key_epoch into _owner, _epoch from public.portfolios where id = _invite.portfolio_id;
  if _owner is null then
    return 'not_found';
  end if;
  if _owner = _uid then
    return 'own_invite';
  end if;

  select lower(email), email_confirmed_at into _email, _confirmed from auth.users where id = _uid;
  if _email is distinct from _invite.invitee_email then
    return 'wrong_account';
  end if;
  if exists (
    select 1 from public.portfolio_members
    where portfolio_id = _invite.portfolio_id and user_id = _uid
  ) then
    return 'already_member';
  end if;
  if _confirmed is null then
    return 'unconfirmed';
  end if;
  if _invite.consumed_at is not null then
    return 'used';
  end if;
  if _invite.expires_at <= now() or _invite.key_epoch <> _epoch then
    return 'expired';
  end if;
  if not public.has_family(_owner) then
    return 'unavailable';
  end if;

  select partner_id into _partner from public.family_partners where owner_id = _owner;
  if _partner is not null and _partner <> _uid then
    return 'seat_taken';
  end if;
  if exists (select 1 from public.family_partners where partner_id = _uid and owner_id <> _owner) then
    return 'already_partnered';
  end if;
  return 'ok';
end;
$$;

-- What the invitee needs to accept: the wrapped PK and its context, plus the
-- inviter's email so they know who it's from. Everything but the status is
-- null unless the status is 'ok'.
create function public.get_portfolio_invite(p_invite_id uuid)
returns table (
  status       text,
  portfolio_id uuid,
  key_epoch    integer,
  wrapped_pk   bytea,
  invited_by   text,
  expires_at   timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  _uid    uuid := auth.uid();
  _invite public.portfolio_invites%rowtype;
  _status text;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into _invite from public.portfolio_invites i where i.id = p_invite_id;
  if not found then
    return query select 'not_found'::text, null::uuid, null::integer, null::bytea, null::text, null::timestamptz;
    return;
  end if;

  _status := public.portfolio_invite_status(_invite, _uid);
  if _status <> 'ok' then
    return query select _status, null::uuid, null::integer, null::bytea, null::text, null::timestamptz;
    return;
  end if;

  return query
    select 'ok'::text, _invite.portfolio_id, _invite.key_epoch, _invite.wrapped_pk_invite,
           (select u.email::text from auth.users u where u.id = _invite.created_by),
           _invite.expires_at;
end;
$$;

-- ---------------------------------------------------------------------------
-- accept_portfolio_invite: single use. The portfolio row is locked first so
-- a rotation can't land between the checks and the insert. The consuming
-- UPDATE repeats the pending/unexpired/epoch conditions, clears the wrap,
-- and takes the seat; the member insert then passes enforce_portfolio_member.
-- ---------------------------------------------------------------------------
create function public.accept_portfolio_invite(p_invite_id uuid, p_wrapped_pk bytea)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  _uid       uuid := auth.uid();
  _invite    public.portfolio_invites%rowtype;
  _portfolio public.portfolios%rowtype;
  _status    text;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into _invite from public.portfolio_invites where id = p_invite_id;
  if not found then
    return 'not_found';
  end if;
  select * into _portfolio from public.portfolios where id = _invite.portfolio_id for update;
  if not found then
    return 'not_found';
  end if;
  -- Re-read under the lock.
  select * into _invite from public.portfolio_invites where id = p_invite_id;

  _status := public.portfolio_invite_status(_invite, _uid);
  if _status <> 'ok' then
    return _status;
  end if;

  update public.portfolio_invites
  set consumed_at = now(), consumed_by = _uid, wrapped_pk_invite = null
  where id = p_invite_id
    and consumed_at is null
    and expires_at > now()
    and key_epoch = _portfolio.key_epoch;
  if not found then
    return 'used';
  end if;

  insert into public.family_partners (owner_id, partner_id)
  values (_portfolio.owner_id, _uid)
  on conflict (owner_id) do nothing;

  insert into public.portfolio_members (portfolio_id, user_id, wrapped_pk, key_epoch)
  values (_portfolio.id, _uid, p_wrapped_pk, _portfolio.key_epoch);

  return 'ok';
end;
$$;

-- ---------------------------------------------------------------------------
-- rotate_portfolio_key: owner only, once the owner is the only member left.
-- Writes the blob re-encrypted under the new PK, replaces the owner's wrap
-- (keeping the old one in portfolio_key_history) and clears rotation_due.
-- Pending invites wrap the old PK and are deleted.
-- ---------------------------------------------------------------------------
create function public.rotate_portfolio_key(
  p_id                uuid,
  p_expected_revision bigint,
  p_expected_epoch    integer,
  p_encrypted_data    bytea,
  p_nonce             bytea,
  p_enc_version       integer,
  p_owner_wrapped_pk  bytea
)
returns table (status text, current_revision bigint, current_epoch integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  _uid uuid := auth.uid();
  _p   public.portfolios%rowtype;
begin
  select * into _p from public.portfolios p where p.id = p_id for update;
  if not found or _p.owner_id <> _uid then
    return query select 'forbidden'::text, null::bigint, null::integer;
    return;
  end if;
  if _p.revision <> p_expected_revision or _p.key_epoch <> p_expected_epoch then
    return query select 'conflict'::text, _p.revision, _p.key_epoch;
    return;
  end if;
  if exists (
    select 1 from public.portfolio_members m
    where m.portfolio_id = p_id and m.user_id <> _uid
  ) then
    return query select 'members_remain'::text, _p.revision, _p.key_epoch;
    return;
  end if;

  insert into public.portfolio_key_history (portfolio_id, key_epoch, user_id, wrapped_pk)
  select m.portfolio_id, m.key_epoch, m.user_id, m.wrapped_pk
  from public.portfolio_members m
  where m.portfolio_id = p_id and m.user_id = _uid
  on conflict do nothing;

  update public.portfolios p
  set encrypted_data = p_encrypted_data,
      nonce          = p_nonce,
      enc_version    = p_enc_version,
      revision       = _p.revision + 1,
      key_epoch      = _p.key_epoch + 1,
      rotation_due   = false
  where p.id = p_id;

  update public.portfolio_members m
  set wrapped_pk = p_owner_wrapped_pk,
      key_epoch  = _p.key_epoch + 1
  where m.portfolio_id = p_id and m.user_id = _uid;

  delete from public.portfolio_invites i
  where i.portfolio_id = p_id and i.consumed_at is null;

  return query select 'ok'::text, _p.revision + 1, _p.key_epoch + 1;
end;
$$;

-- ---------------------------------------------------------------------------
-- list_portfolio_people: the members of every portfolio the caller is in,
-- with their emails, so each side can see who the portfolio is shared with.
-- ---------------------------------------------------------------------------
create function public.list_portfolio_people()
returns table (portfolio_id uuid, user_id uuid, email text, is_owner boolean, joined_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select m.portfolio_id, m.user_id, u.email::text, p.owner_id = m.user_id, m.created_at
  from public.portfolio_members m
  join public.portfolios p on p.id = m.portfolio_id
  join auth.users u on u.id = m.user_id
  where m.portfolio_id in (
    select mine.portfolio_id from public.portfolio_members mine where mine.user_id = auth.uid()
  )
  order by m.portfolio_id, m.created_at;
$$;

-- ---------------------------------------------------------------------------
-- release_owned_portfolios: run before an account's own rows are deleted
-- (account deletion, and the wipe after a password reset without a recovery
-- code). A portfolio with a partner passes to the partner, who already holds
-- its key; the others are deleted. Service role only.
-- ---------------------------------------------------------------------------
create function public.release_owned_portfolios(p_user_id uuid)
returns table (transferred integer, deleted integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  _row         record;
  _transferred integer := 0;
  _deleted     integer := 0;
begin
  for _row in
    select p.id,
           (select m.user_id from public.portfolio_members m
            where m.portfolio_id = p.id and m.user_id <> p_user_id
            limit 1) as heir
    from public.portfolios p
    where p.owner_id = p_user_id
    for update of p
  loop
    if _row.heir is not null then
      update public.portfolios set owner_id = _row.heir where id = _row.id;
      _transferred := _transferred + 1;
    else
      delete from public.portfolios where id = _row.id;
      _deleted := _deleted + 1;
    end if;
  end loop;

  delete from public.family_partners where owner_id = p_user_id;
  return query select _transferred, _deleted;
end;
$$;

-- ---------------------------------------------------------------------------
-- Function grants
-- ---------------------------------------------------------------------------
revoke execute on function public.stamp_portfolio_save()                                   from public, anon, authenticated;
revoke execute on function public.enforce_portfolio_member()                               from public, anon, authenticated;
revoke execute on function public.after_portfolio_member_removed()                         from public, anon, authenticated;
revoke execute on function public.record_portfolio_revision()                              from public, anon, authenticated;
revoke execute on function public.has_family(uuid)                                         from public, anon, authenticated;
revoke execute on function public.portfolio_invite_status(public.portfolio_invites, uuid)  from public, anon, authenticated;
revoke execute on function public.release_owned_portfolios(uuid)                           from public, anon, authenticated;
revoke execute on function public.is_portfolio_owner(uuid)                                 from public, anon;
revoke execute on function public.create_portfolio_invite(uuid, uuid, text, bytea, integer) from public, anon;
revoke execute on function public.get_portfolio_invite(uuid)                               from public, anon;
revoke execute on function public.accept_portfolio_invite(uuid, bytea)                     from public, anon;
revoke execute on function public.rotate_portfolio_key(uuid, bigint, integer, bytea, bytea, integer, bytea) from public, anon;
revoke execute on function public.list_portfolio_people()                                  from public, anon;

grant execute on function public.has_family(uuid)                                          to service_role;
grant execute on function public.release_owned_portfolios(uuid)                            to service_role;
grant execute on function public.is_portfolio_owner(uuid)                                  to authenticated, service_role;
grant execute on function public.create_portfolio_invite(uuid, uuid, text, bytea, integer) to authenticated, service_role;
grant execute on function public.get_portfolio_invite(uuid)                                to authenticated, service_role;
grant execute on function public.accept_portfolio_invite(uuid, bytea)                      to authenticated, service_role;
grant execute on function public.rotate_portfolio_key(uuid, bigint, integer, bytea, bytea, integer, bytea) to authenticated, service_role;
grant execute on function public.list_portfolio_people()                                   to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Daily purge: expired invites, and used ones after 30 days (kept that long
-- so a partner reopening the link is told it's used, not that it's unknown).
-- 03:20 UTC, offset from the other nightly jobs.
-- ---------------------------------------------------------------------------
create extension if not exists pg_cron with schema extensions;

select cron.schedule(
  'portfolio-invites-purge-daily',
  '20 3 * * *',
  $$
  delete from public.portfolio_invites
  where (consumed_at is null and expires_at < now())
     or consumed_at < now() - interval '30 days'
  $$
);
